window.ARK_MAPS = {
  "the-island": {
    name: "The Island",
    wikiPage: "The_Island",
    wikiMapName: "The Island",
    mapFile: "The Island Topographic Map.jpg",
    type: "Base Map",
    released: "2023-10-25",
    resourceUrl: null
  },
  "scorched-earth": {
    name: "Scorched Earth",
    wikiPage: "Scorched_Earth",
    wikiMapName: "Scorched Earth",
    mapFile: "Scorched Earth Topographic Map.jpg",
    type: "Story Map",
    released: "2024-04-01",
    resourceUrl: null
  },
  "the-center": {
    name: "The Center",
    wikiPage: "The_Center",
    wikiMapName: "The Center",
    mapFile: "The Center Topographic Map.jpg",
    type: "Expansion Map",
    released: "2024-06-04",
    resourceUrl: null
  },
  "aberration": {
    name: "Aberration",
    wikiPage: "Aberration",
    wikiMapName: "Aberration",
    mapFile: "Aberration Topographic Map.jpg",
    type: "Story Map",
    released: "2024-09-05",
    resourceUrl: null
  },
  "extinction": {
    name: "Extinction",
    wikiPage: "Extinction",
    wikiMapName: "Extinction",
    mapFile: "Extinction Topographic Map.jpg",
    type: "Story Map",
    released: "2024-12-19",
    resourceUrl: null
  },
  "astraeos": {
    name: "Astraeos",
    wikiPage: "Astraeos",
    wikiMapName: "Astraeos",
    mapFile: "Astraeos Map ASA.jpg",
    type: "Expansion Map",
    released: "2025-02-14",
    resourceUrl: "astraeos/resources.html",
    current: true
  },
  "ragnarok": {
    name: "Ragnarok",
    wikiPage: "Ragnarok",
    wikiMapName: "Ragnarok",
    mapFile: "Ragnarok Ocean Topographic Map.jpg",
    type: "Expansion Map",
    released: "2025-06-20",
    resourceUrl: null
  },
  "valguero": {
    name: "Valguero",
    wikiPage: "Valguero",
    wikiMapName: "Valguero",
    mapFile: "Valguero Topographic Map.jpg",
    type: "Expansion Map",
    released: "2025-10-07",
    resourceUrl: null
  },
  "lost-colony": {
    name: "Lost Colony",
    wikiPage: "Lost_Colony",
    wikiMapName: "Lost Colony",
    mapFile: "Lost Colony Map ASA.jpg",
    type: "Story Expansion",
    released: "2025-12-19",
    resourceUrl: null
  },
  "genesis-part-1": {
    name: "Genesis: Part 1",
    wikiPage: "Genesis:_Part_1",
    wikiMapName: "Genesis Part 1",
    mapFile: "Genesis Part 1 Topographic Map.jpg",
    type: "Story Map",
    released: "2026-07-03",
    resourceUrl: null
  }
};

window.ARK_CREATURE_ALIASES = {
  "Achatina": "アフリカマイマイ カタツムリ",
  "Allosaurus": "アロサウルス アロ",
  "Ankylosaurus": "アンキロサウルス アンキロ",
  "Araneo": "アラネオモーフス クモ 蜘蛛",
  "Argentavis": "アルゲンタヴィス アルゲン",
  "Arthropluera": "アースロプレウラ ムカデ",
  "Baryonyx": "バリオニクス バリオ",
  "Basilisk": "バジリスク",
  "Basilosaurus": "バシロサウルス バシロ",
  "Beelzebufo": "ベールゼブフォ カエル",
  "Bison": "バイソン",
  "Bloodstalker": "ブラッドストーカー",
  "Boaratos": "ボアラトス",
  "Brontosaurus": "ブロントサウルス ブロント",
  "Bulbdog": "バルブドッグ",
  "Burrowbuck": "ブローバック",
  "Carbonemys": "カルボネミス カメ 亀",
  "Carcharodontosaurus": "カルカロドントサウルス カルカロ",
  "Carnotaurus": "カルノタウルス カルノ",
  "Castoroides": "カストロイデス ビーバー",
  "Ceratosaurus": "ケラトサウルス",
  "Chalicotherium": "カリコテリウム",
  "Concavenator": "コンカヴェナトル コンカベナトル",
  "Daeodon": "ダエオドン",
  "Deinonychus": "デイノニクス",
  "Deinosuchus": "デイノスクス",
  "Dilophosaur": "ディロフォサウルス ディロ",
  "Dire Bear": "ダイアベア",
  "Direwolf": "ダイアウルフ",
  "Dodo": "ドードー",
  "Doedicurus": "ドエディクルス ドエディ",
  "Dung Beetle": "フンコロガシ 糞ころがし",
  "Equus": "エクウス 馬",
  "Fasolasuchus": "ファソラスクス",
  "Ferox": "フェロックス",
  "Gacha": "ガチャ",
  "Gallimimus": "ガリミムス",
  "Giganotosaurus": "ギガノトサウルス ギガ",
  "Gigantoraptor": "ギガントラプトル",
  "Griffin": "グリフィン",
  "Iguanodon": "イグアノドン",
  "Karkinos": "カルキノス カニ 蟹",
  "Mammoth": "マンモス",
  "Managarmr": "マナガルム",
  "Mantis": "カマキリ マンティス",
  "Megachelon": "メガケロン",
  "Megalodon": "メガロドン サメ 鮫",
  "Megatherium": "メガテリウム",
  "Megaraptor": "メガラプトル",
  "Morellatops": "モレラトプス",
  "Moschops": "モスコプス",
  "Oasisaur": "オアシサウルス",
  "Otter": "カワウソ",
  "Oviraptor": "オヴィラプトル オビラプトル",
  "Ovis": "オヴィス 羊 ヒツジ",
  "Parasaur": "パラサウロロフス パラサウルス パラサウロ",
  "Phoenix": "フェニックス",
  "Procoptodon": "プロコプトドン カンガルー",
  "Pteranodon": "プテラノドン プテラ",
  "Quetzal": "ケツァル",
  "Raptor": "ラプトル",
  "Ravager": "ラベジャー",
  "Rex": "レックス ティラノサウルス ティラノ",
  "Rock Drake": "ロックドレイク ドレイク",
  "Rock Elemental": "ロックエレメンタル ゴーレム",
  "Roll Rat": "ロールラット",
  "Sabertooth": "サーベルタイガー サーベル",
  "Sarco": "サルコスクス サルコ",
  "Shinehorn": "シャインホーン",
  "Snow Owl": "スノーオウル フクロウ",
  "Spino": "スピノサウルス スピノ",
  "Stegosaurus": "ステゴサウルス ステゴ",
  "Tapejara": "タペヤラ",
  "Therizinosaur": "テリジノサウルス テリジノ",
  "Thorny Dragon": "モロクトカゲ ソーニードラゴン",
  "Thylacoleo": "ティラコレオ",
  "Titanosaur": "ティタノサウルス ティタノ",
  "Triceratops": "トリケラトプス トリケラ",
  "Tusoteuthis": "トゥソテウティス イカ 烏賊",
  "Velonasaur": "ベロナサウルス",
  "Wyvern": "ワイバーン",
  "Yutyrannus": "ユウティラヌス ユウティ"
};

window.ARK_CREATURE_OVERRIDES = {
  "astraeos|Burrowbuck": "astraeos/creatures/burrowbuck.html"
};
